# Generated by Django 5.0.6 on 2024-05-27 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=20)),
                ('login_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(max_length=10)),
                ('balance', models.FloatField(default=25000)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(unique=True)),
                ('transaction_type', models.CharField(max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('atm_balance', models.FloatField(default=500000)),
                ('bankaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.bankaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.bankaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('authmanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='e_cash.authmanager')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=20)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.role')),
            ],
            bases=('e_cash.authmanager',),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.user'),
        ),
    ]
