# Generated by Django 5.0.6 on 2024-05-31 19:53

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(default='adminecd8bef7-0cee-4b25-a071-47ff2391a3a8', max_length=64, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('atm_id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('atm_balance', models.FloatField(default=500000)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(default=uuid.uuid5, max_length=120, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('password', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('tel', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricle', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('password', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('tel', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(max_length=10)),
                ('balance', models.FloatField(default=25000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.client')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAdmin',
            fields=[
                ('admin_id', models.CharField(db_index=True, default='adminecd8bef7-0cee-4b25-a071-47ff2391a3a8', max_length=64)),
                ('username', models.CharField(max_length=20)),
                ('time_created', models.DateTimeField(blank=True, editable=False)),
                ('password', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical admin',
                'verbose_name_plural': 'historical admins',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalATM',
            fields=[
                ('atm_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('location', models.CharField(max_length=20)),
                ('atm_balance', models.FloatField(default=500000)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical atm',
                'verbose_name_plural': 'historical atms',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBankCard',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=20)),
                ('account_type', models.CharField(max_length=10)),
                ('balance', models.FloatField(default=25000)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='e_cash.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bank card',
                'verbose_name_plural': 'historical bank cards',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('client_id', models.CharField(db_index=True, default=uuid.uuid5, max_length=120)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=50)),
                ('time_created', models.DateTimeField(blank=True, editable=False)),
                ('password', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('tel', models.PositiveBigIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical client',
                'verbose_name_plural': 'historical clients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('matricle', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=50)),
                ('time_created', models.DateTimeField(blank=True, editable=False)),
                ('password', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('tel', models.PositiveBigIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee',
                'verbose_name_plural': 'historical employees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('transaction_id', models.CharField(db_index=True, default=uuid.uuid4)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=20)),
                ('transaction_date', models.DateTimeField(blank=True, editable=False)),
                ('transaction_amount', models.FloatField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical transaction',
                'verbose_name_plural': 'historical transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocuments',
            fields=[
                ('document_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=120)),
                ('doc', models.TextField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='e_cash.transaction')),
            ],
            options={
                'verbose_name': 'historical documents',
                'verbose_name_plural': 'historical documentss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False)),
                ('doc', models.FileField(upload_to='documents/')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ATMTransactAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.atm')),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.bankcard')),
                ('emp_matricle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_cash.employee')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.bankcard')),
                ('emp_matricle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.employee')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.transaction')),
            ],
        ),
    ]
