# Generated by Django 5.0.6 on 2024-05-30 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=20)),
                ('login_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(max_length=10)),
                ('balance', models.FloatField(default=25000)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('authmanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='e_cash.authmanager')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('password', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('tel', models.PositiveBigIntegerField()),
            ],
            bases=('e_cash.authmanager',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('authmanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='e_cash.authmanager')),
                ('matricle', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('password', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('tel', models.PositiveBigIntegerField()),
            ],
            bases=('e_cash.authmanager',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(unique=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.FloatField()),
                ('documents', models.ManyToManyField(blank=True, to='e_cash.document')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('atm_balance', models.FloatField(default=500000)),
                ('bankcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.bankcard')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='bankcard',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_cash.client'),
        ),
    ]
