# Generated by Django 5.0.6 on 2024-05-31 19:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(default='admina7fdc3ff-6c6e-4dd9-8b1e-38640019967f', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicaladmin',
            name='admin_id',
            field=models.CharField(db_index=True, default='admina7fdc3ff-6c6e-4dd9-8b1e-38640019967f', max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='client_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=120),
        ),
    ]
