# Generated by Django 5.0.6 on 2024-05-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_cash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
