# Generated by Django 5.0.6 on 2024-05-31 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cash', '0002_alter_admin_admin_id_alter_client_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcard',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historicalbankcard',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='historicalbankcard',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(default='admin7701e18b-0812-4de4-a20a-9c98182eac19', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='account_number',
            field=models.CharField(default=uuid.uuid4, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaladmin',
            name='admin_id',
            field=models.CharField(db_index=True, default='admin7701e18b-0812-4de4-a20a-9c98182eac19', max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalbankcard',
            name='account_number',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=20),
        ),
    ]
