# Generated by Django 5.0.6 on 2024-05-30 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cash', '0002_document_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atm',
            name='bankcard',
        ),
        migrations.RemoveField(
            model_name='atm',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='atm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_cash.atm'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_cash.employee'),
        ),
    ]
