# Generated by Django 5.0.6 on 2024-05-31 20:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cash', '0003_remove_bankcard_account_type_remove_bankcard_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(default='adminc2ae665e-27ed-4d62-80aa-25dcaeee5af0', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='account_number',
            field=models.CharField(default=uuid.uuid4, max_length=86, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaladmin',
            name='admin_id',
            field=models.CharField(db_index=True, default='adminc2ae665e-27ed-4d62-80aa-25dcaeee5af0', max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalbankcard',
            name='account_number',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=86),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='transaction_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=86),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, max_length=86, primary_key=True, serialize=False, unique=True),
        ),
    ]
