# Generated by Django 5.0.6 on 2024-06-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cash', '0004_alter_admin_admin_id_alter_bankcard_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(default='admin7c359da9-d397-48d6-93a1-cd26361a992f', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='matricle',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicaladmin',
            name='admin_id',
            field=models.CharField(db_index=True, default='admin7c359da9-d397-48d6-93a1-cd26361a992f', max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='matricle',
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
