# Generated by Django 5.0.6 on 2024-06-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cash', '0005_remove_employee_id_remove_historicalemployee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(default='admin00376794-66a3-4dfb-aacf-ae1e0cc97b0a', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicaladmin',
            name='admin_id',
            field=models.CharField(db_index=True, default='admin00376794-66a3-4dfb-aacf-ae1e0cc97b0a', max_length=64),
        ),
    ]
