# Generated by Django 5.0.6 on 2024-06-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cash', '0006_alter_admin_admin_id_alter_historicaladmin_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(default='admin9c73847b-73f7-4224-b424-ecc10883cb14', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicaladmin',
            name='admin_id',
            field=models.CharField(db_index=True, default='admin9c73847b-73f7-4224-b424-ecc10883cb14', max_length=64),
        ),
    ]
