# Generated by Django 5.0.6 on 2024-06-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cash', '0007_alter_admin_admin_id_alter_historicaladmin_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(default='adminb3b99529-0279-4427-af6a-874fd70cc8c4', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='matricle',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicaladmin',
            name='admin_id',
            field=models.CharField(db_index=True, default='adminb3b99529-0279-4427-af6a-874fd70cc8c4', max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='matricle',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
